//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseAutomationService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.200")]
        public string HomematicServerAddress {
            get {
                return ((string)(this["HomematicServerAddress"]));
            }
            set {
                this["HomematicServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9696")]
        public int WebServerListenPort {
            get {
                return ((int)(this["WebServerListenPort"]));
            }
            set {
                this["WebServerListenPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int HumidityAutomationRefencePoint {
            get {
                return ((int)(this["HumidityAutomationRefencePoint"]));
            }
            set {
                this["HumidityAutomationRefencePoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int HumidityAutomationHysteresis {
            get {
                return ((int)(this["HumidityAutomationHysteresis"]));
            }
            set {
                this["HumidityAutomationHysteresis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01:00:00")]
        public global::System.TimeSpan HumidityAutomationMaxOnTime {
            get {
                return ((global::System.TimeSpan)(this["HumidityAutomationMaxOnTime"]));
            }
            set {
                this["HumidityAutomationMaxOnTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:15:00")]
        public global::System.TimeSpan HumidityAutomationMinOnTime {
            get {
                return ((global::System.TimeSpan)(this["HumidityAutomationMinOnTime"]));
            }
            set {
                this["HumidityAutomationMinOnTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan HumidityAutomationMinOffTime {
            get {
                return ((global::System.TimeSpan)(this["HumidityAutomationMinOffTime"]));
            }
            set {
                this["HumidityAutomationMinOffTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int HeatingAutomationRefencePoint {
            get {
                return ((int)(this["HeatingAutomationRefencePoint"]));
            }
            set {
                this["HeatingAutomationRefencePoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int HeatingAutomationHysteresis {
            get {
                return ((int)(this["HeatingAutomationHysteresis"]));
            }
            set {
                this["HeatingAutomationHysteresis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan HeatingAutomationMaxOnTime {
            get {
                return ((global::System.TimeSpan)(this["HeatingAutomationMaxOnTime"]));
            }
            set {
                this["HeatingAutomationMaxOnTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:30")]
        public global::System.TimeSpan HeatingAutomationMinOnTime {
            get {
                return ((global::System.TimeSpan)(this["HeatingAutomationMinOnTime"]));
            }
            set {
                this["HeatingAutomationMinOnTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:02:00")]
        public global::System.TimeSpan heatingAutomationMinOffTime {
            get {
                return ((global::System.TimeSpan)(this["heatingAutomationMinOffTime"]));
            }
            set {
                this["heatingAutomationMinOffTime"] = value;
            }
        }
    }
}
